# Generated by Django 5.0.6 on 2026-09-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Anything Automation', max_length=150)),
                ('tagline', models.CharField(default='Automate. Innovate. Elevate.', max_length=200)),
                ('hero_subtitle', models.CharField(default='Powering Industries with Intelligent Automation Solutions', max_length=250)),
                ('about_text', models.TextField(default='We provide end-to-end industrial automation solutions that improve efficiency, ensure reliability, and drive productivity. With 8+ years of experience and a team of skilled professionals, we deliver innovative and cost-effective solutions tailored to the unique needs of every industry.')),
                ('years_of_experience', models.PositiveIntegerField(default=8)),
                ('gst_number', models.CharField(blank=True, max_length=20)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('address_line', models.CharField(blank=True, max_length=255)),
                ('locality', models.CharField(blank=True, max_length=150)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
            ],
            options={
                'verbose_name': 'Company Profile',
                'verbose_name_plural': 'Company Profile',
            },
        ),
        migrations.CreateModel(
            name='WhyChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Why Choose Us items',
                'ordering': ['order'],
            },
        ),
    ]
